---
name: 刀 Day Ahead Optimizer - Beta
version: 2025.5.0.rc
slug: day_ahead_opt_beta
description: Docker used by Home Assistant Community Add-ons for day ahead optimizations (Beta)
url: https://github.com/corneel27/day-ahead/
codenotary: cees.van.beek@xs4all.nl
arch:
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_port: 5000
panel_admin: false
panel_icon: mdi:home-battery-outline
apparmor: true
legacy: true
map:
  - ssl:rw
  - addon_config:rw
  - homeassistant_config:rw
homeassistant_api: true
ports:
  5000/tcp: 5000
image: "corneel27/dao-{arch}"
version: addon

